name: Build site
on: [push]
jobs:
    JobName:
        runs-on: ubuntu-latest
        env:
            GH_PAGES_BRANCH: gh-pages
            GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
        steps:
         - uses: actions/checkout@v2
         - uses: nelsonjchen/gh-pages-pelican-action@0.1.10
         - run: echo 'Building pelican site'
