name: Build and deploy Pelican site
on: 
    pull_request:
        types: [closed]
    push:
        branches:
            - master

jobs:
    build_deploy_ghpages:
        runs-on: ubuntu-latest
        env:
            GH_PAGES_BRANCH: gh-pages
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
         - uses: actions/checkout@v2
         - uses: nelsonjchen/gh-pages-pelican-action@0.1.10
         - run: |  
            curl -X PUT \
            -u poiley:${{ secrets.GITHUB_TOKEN }} \
            -H "Accept: application/vnd.github.v3+json" \ 
            https://api.github.com/repos/poiley/poiley.github.io/pages \
            -d '{"cname":"poile.dev"}'