name: Build and deploy Pelican site
on: 
    pull_request:
        types: [closed]
    push:
        branches:
            - master

jobs:
    build_deploy_ghpages:
        runs-on: ubuntu-latest
        env:
            GH_PAGES_BRANCH: gh-pages
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
          - uses: actions/checkout@v2
          - uses: nelsonjchen/gh-pages-pelican-action@0.1.10
          - uses: octokit/request-action@v2.x
            id: cname_update
            with:
                route: GET /repos/{owner}/{repo}/pages
                owner: poiley
                repo: poiley.github.io
                cname: poile.dev